version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      REDIS_URL: ${REDIS_URL}
      AI_API_KEY_CHATBOT: ${AI_API_KEY_CHATBOT}
      AI_API_KEY_RECC: ${AI_API_KEY_RECC}
      AI_API_KEY_CODE_FIX: ${AI_API_KEY_CODE_FIX}

  frontend:
    build:
      context: .
      dockerfile: apps/platform/Dockerfile
      args:
        VITE_PUBLIC_BACKEND_URL: ${VITE_PUBLIC_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      - backend