app = "a11yguard-backend"
primary_region = "bom"

[build]
  image = "talhadevelopes/a11yguard-backend:latest"

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 4000
  min_machines_running = 0